frequency_range:
  end: 1000.0
  num_points: 1000
  start: 0.0
noise_floor_params:
  base_amplitude: 5.0
  high_energy_amplitude: 2.0
  high_energy_frequency: 1000.0
  low_energy_amplitude: 1.0
  low_energy_frequency: 0.01
signal_spike_params:
- amplitude: 40.0
  mu: 350.0
  sigma: 10.0
